//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSharpParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICSharpParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class CSharpParserBaseListener : ICSharpParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] CSharpParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] CSharpParser.CompilationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.usingDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingDeclaration([NotNull] CSharpParser.UsingDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.usingDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingDeclaration([NotNull] CSharpParser.UsingDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.attributeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributeDeclaration([NotNull] CSharpParser.AttributeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.attributeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributeDeclaration([NotNull] CSharpParser.AttributeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclaration([NotNull] CSharpParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclaration([NotNull] CSharpParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] CSharpParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] CSharpParser.ModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.classOrInterfaceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassOrInterfaceModifier([NotNull] CSharpParser.ClassOrInterfaceModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.classOrInterfaceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassOrInterfaceModifier([NotNull] CSharpParser.ClassOrInterfaceModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableModifier([NotNull] CSharpParser.VariableModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableModifier([NotNull] CSharpParser.VariableModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] CSharpParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] CSharpParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParameters([NotNull] CSharpParser.TypeParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParameters([NotNull] CSharpParser.TypeParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParameter([NotNull] CSharpParser.TypeParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParameter([NotNull] CSharpParser.TypeParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeBound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeBound([NotNull] CSharpParser.TypeBoundContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeBound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeBound([NotNull] CSharpParser.TypeBoundContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclaration([NotNull] CSharpParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclaration([NotNull] CSharpParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.enumConstants"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumConstants([NotNull] CSharpParser.EnumConstantsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.enumConstants"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumConstants([NotNull] CSharpParser.EnumConstantsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.enumConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumConstant([NotNull] CSharpParser.EnumConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.enumConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumConstant([NotNull] CSharpParser.EnumConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.enumBodyDeclarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBodyDeclarations([NotNull] CSharpParser.EnumBodyDeclarationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.enumBodyDeclarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBodyDeclarations([NotNull] CSharpParser.EnumBodyDeclarationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.interfaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDeclaration([NotNull] CSharpParser.InterfaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.interfaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDeclaration([NotNull] CSharpParser.InterfaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] CSharpParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] CSharpParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.interfaceBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceBody([NotNull] CSharpParser.InterfaceBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.interfaceBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceBody([NotNull] CSharpParser.InterfaceBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBodyDeclaration([NotNull] CSharpParser.ClassBodyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBodyDeclaration([NotNull] CSharpParser.ClassBodyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberDeclaration([NotNull] CSharpParser.MemberDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberDeclaration([NotNull] CSharpParser.MemberDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDeclaration([NotNull] CSharpParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDeclaration([NotNull] CSharpParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodBody([NotNull] CSharpParser.MethodBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodBody([NotNull] CSharpParser.MethodBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeTypeOrVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeTypeOrVoid([NotNull] CSharpParser.TypeTypeOrVoidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeTypeOrVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeTypeOrVoid([NotNull] CSharpParser.TypeTypeOrVoidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.genericMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericMethodDeclaration([NotNull] CSharpParser.GenericMethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.genericMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericMethodDeclaration([NotNull] CSharpParser.GenericMethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.genericConstructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericConstructorDeclaration([NotNull] CSharpParser.GenericConstructorDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.genericConstructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericConstructorDeclaration([NotNull] CSharpParser.GenericConstructorDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.constructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorDeclaration([NotNull] CSharpParser.ConstructorDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.constructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorDeclaration([NotNull] CSharpParser.ConstructorDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDeclaration([NotNull] CSharpParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDeclaration([NotNull] CSharpParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.interfaceBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceBodyDeclaration([NotNull] CSharpParser.InterfaceBodyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.interfaceBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceBodyDeclaration([NotNull] CSharpParser.InterfaceBodyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.interfaceMemberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMemberDeclaration([NotNull] CSharpParser.InterfaceMemberDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.interfaceMemberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMemberDeclaration([NotNull] CSharpParser.InterfaceMemberDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.constDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstDeclaration([NotNull] CSharpParser.ConstDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.constDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstDeclaration([NotNull] CSharpParser.ConstDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.constantDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantDeclarator([NotNull] CSharpParser.ConstantDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.constantDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantDeclarator([NotNull] CSharpParser.ConstantDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.interfaceMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMethodDeclaration([NotNull] CSharpParser.InterfaceMethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.interfaceMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMethodDeclaration([NotNull] CSharpParser.InterfaceMethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.interfaceMethodModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMethodModifier([NotNull] CSharpParser.InterfaceMethodModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.interfaceMethodModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMethodModifier([NotNull] CSharpParser.InterfaceMethodModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.genericInterfaceMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericInterfaceMethodDeclaration([NotNull] CSharpParser.GenericInterfaceMethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.genericInterfaceMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericInterfaceMethodDeclaration([NotNull] CSharpParser.GenericInterfaceMethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.variableDeclarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarators([NotNull] CSharpParser.VariableDeclaratorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.variableDeclarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarators([NotNull] CSharpParser.VariableDeclaratorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarator([NotNull] CSharpParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarator([NotNull] CSharpParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaratorId([NotNull] CSharpParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaratorId([NotNull] CSharpParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableInitializer([NotNull] CSharpParser.VariableInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableInitializer([NotNull] CSharpParser.VariableInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.arrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayInitializer([NotNull] CSharpParser.ArrayInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.arrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayInitializer([NotNull] CSharpParser.ArrayInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.classOrInterfaceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassOrInterfaceType([NotNull] CSharpParser.ClassOrInterfaceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.classOrInterfaceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassOrInterfaceType([NotNull] CSharpParser.ClassOrInterfaceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArgument([NotNull] CSharpParser.TypeArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArgument([NotNull] CSharpParser.TypeArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.qualifiedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedNameList([NotNull] CSharpParser.QualifiedNameListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.qualifiedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedNameList([NotNull] CSharpParser.QualifiedNameListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameters([NotNull] CSharpParser.FormalParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameters([NotNull] CSharpParser.FormalParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterList([NotNull] CSharpParser.FormalParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterList([NotNull] CSharpParser.FormalParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameter([NotNull] CSharpParser.FormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameter([NotNull] CSharpParser.FormalParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.lastFormalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLastFormalParameter([NotNull] CSharpParser.LastFormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.lastFormalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLastFormalParameter([NotNull] CSharpParser.LastFormalParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] CSharpParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] CSharpParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] CSharpParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] CSharpParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteral([NotNull] CSharpParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteral([NotNull] CSharpParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatLiteral([NotNull] CSharpParser.FloatLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatLiteral([NotNull] CSharpParser.FloatLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] CSharpParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] CSharpParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.elementValuePairs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementValuePairs([NotNull] CSharpParser.ElementValuePairsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.elementValuePairs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementValuePairs([NotNull] CSharpParser.ElementValuePairsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.elementValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementValuePair([NotNull] CSharpParser.ElementValuePairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.elementValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementValuePair([NotNull] CSharpParser.ElementValuePairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.elementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementValue([NotNull] CSharpParser.ElementValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.elementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementValue([NotNull] CSharpParser.ElementValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.elementValueArrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementValueArrayInitializer([NotNull] CSharpParser.ElementValueArrayInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.elementValueArrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementValueArrayInitializer([NotNull] CSharpParser.ElementValueArrayInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.annotationTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationTypeDeclaration([NotNull] CSharpParser.AnnotationTypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.annotationTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationTypeDeclaration([NotNull] CSharpParser.AnnotationTypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.annotationTypeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationTypeBody([NotNull] CSharpParser.AnnotationTypeBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.annotationTypeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationTypeBody([NotNull] CSharpParser.AnnotationTypeBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.annotationTypeElementDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationTypeElementDeclaration([NotNull] CSharpParser.AnnotationTypeElementDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.annotationTypeElementDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationTypeElementDeclaration([NotNull] CSharpParser.AnnotationTypeElementDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.annotationTypeElementRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationTypeElementRest([NotNull] CSharpParser.AnnotationTypeElementRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.annotationTypeElementRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationTypeElementRest([NotNull] CSharpParser.AnnotationTypeElementRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.annotationMethodOrConstantRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationMethodOrConstantRest([NotNull] CSharpParser.AnnotationMethodOrConstantRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.annotationMethodOrConstantRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationMethodOrConstantRest([NotNull] CSharpParser.AnnotationMethodOrConstantRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.annotationMethodRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationMethodRest([NotNull] CSharpParser.AnnotationMethodRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.annotationMethodRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationMethodRest([NotNull] CSharpParser.AnnotationMethodRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.annotationConstantRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationConstantRest([NotNull] CSharpParser.AnnotationConstantRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.annotationConstantRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationConstantRest([NotNull] CSharpParser.AnnotationConstantRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.defaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultValue([NotNull] CSharpParser.DefaultValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.defaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultValue([NotNull] CSharpParser.DefaultValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] CSharpParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] CSharpParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStatement([NotNull] CSharpParser.BlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStatement([NotNull] CSharpParser.BlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclaration([NotNull] CSharpParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclaration([NotNull] CSharpParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.localTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalTypeDeclaration([NotNull] CSharpParser.LocalTypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.localTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalTypeDeclaration([NotNull] CSharpParser.LocalTypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CSharpParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CSharpParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.catchClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCatchClause([NotNull] CSharpParser.CatchClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.catchClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCatchClause([NotNull] CSharpParser.CatchClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.catchType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCatchType([NotNull] CSharpParser.CatchTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.catchType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCatchType([NotNull] CSharpParser.CatchTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.finallyBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinallyBlock([NotNull] CSharpParser.FinallyBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.finallyBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinallyBlock([NotNull] CSharpParser.FinallyBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.resourceSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResourceSpecification([NotNull] CSharpParser.ResourceSpecificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.resourceSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResourceSpecification([NotNull] CSharpParser.ResourceSpecificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.resources"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResources([NotNull] CSharpParser.ResourcesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.resources"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResources([NotNull] CSharpParser.ResourcesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResource([NotNull] CSharpParser.ResourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResource([NotNull] CSharpParser.ResourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.switchBlockStatementGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBlockStatementGroup([NotNull] CSharpParser.SwitchBlockStatementGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.switchBlockStatementGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBlockStatementGroup([NotNull] CSharpParser.SwitchBlockStatementGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchLabel([NotNull] CSharpParser.SwitchLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchLabel([NotNull] CSharpParser.SwitchLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForControl([NotNull] CSharpParser.ForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForControl([NotNull] CSharpParser.ForControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForInit([NotNull] CSharpParser.ForInitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForInit([NotNull] CSharpParser.ForInitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.enhancedForControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnhancedForControl([NotNull] CSharpParser.EnhancedForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.enhancedForControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnhancedForControl([NotNull] CSharpParser.EnhancedForControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParExpression([NotNull] CSharpParser.ParExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParExpression([NotNull] CSharpParser.ParExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] CSharpParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] CSharpParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCall([NotNull] CSharpParser.MethodCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCall([NotNull] CSharpParser.MethodCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CSharpParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CSharpParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.lambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaExpression([NotNull] CSharpParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.lambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaExpression([NotNull] CSharpParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.lambdaParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaParameters([NotNull] CSharpParser.LambdaParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.lambdaParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaParameters([NotNull] CSharpParser.LambdaParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.lambdaBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaBody([NotNull] CSharpParser.LambdaBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.lambdaBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaBody([NotNull] CSharpParser.LambdaBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] CSharpParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] CSharpParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.classType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassType([NotNull] CSharpParser.ClassTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.classType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassType([NotNull] CSharpParser.ClassTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreator([NotNull] CSharpParser.CreatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreator([NotNull] CSharpParser.CreatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreatedName([NotNull] CSharpParser.CreatedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreatedName([NotNull] CSharpParser.CreatedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.innerCreator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInnerCreator([NotNull] CSharpParser.InnerCreatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.innerCreator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInnerCreator([NotNull] CSharpParser.InnerCreatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.arrayCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayCreatorRest([NotNull] CSharpParser.ArrayCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.arrayCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayCreatorRest([NotNull] CSharpParser.ArrayCreatorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassCreatorRest([NotNull] CSharpParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassCreatorRest([NotNull] CSharpParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.explicitGenericInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicitGenericInvocation([NotNull] CSharpParser.ExplicitGenericInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.explicitGenericInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicitGenericInvocation([NotNull] CSharpParser.ExplicitGenericInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArgumentsOrDiamond([NotNull] CSharpParser.TypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArgumentsOrDiamond([NotNull] CSharpParser.TypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonWildcardTypeArgumentsOrDiamond([NotNull] CSharpParser.NonWildcardTypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonWildcardTypeArgumentsOrDiamond([NotNull] CSharpParser.NonWildcardTypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.nonWildcardTypeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonWildcardTypeArguments([NotNull] CSharpParser.NonWildcardTypeArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.nonWildcardTypeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonWildcardTypeArguments([NotNull] CSharpParser.NonWildcardTypeArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeList([NotNull] CSharpParser.TypeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeList([NotNull] CSharpParser.TypeListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeType([NotNull] CSharpParser.TypeTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeType([NotNull] CSharpParser.TypeTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] CSharpParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] CSharpParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArguments([NotNull] CSharpParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArguments([NotNull] CSharpParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.superSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperSuffix([NotNull] CSharpParser.SuperSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.superSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperSuffix([NotNull] CSharpParser.SuperSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.explicitGenericInvocationSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicitGenericInvocationSuffix([NotNull] CSharpParser.ExplicitGenericInvocationSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.explicitGenericInvocationSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicitGenericInvocationSuffix([NotNull] CSharpParser.ExplicitGenericInvocationSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] CSharpParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] CSharpParser.ArgumentsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
